Name = input("이름을 입력하세요: ")
Number = input("학번을 입력하세요: ")
Major = input("학과를 입력하세요: ")  
Grade = input("학년을 입력하세요: ")  

print("\n")
print("<출력>")
print("이름:", Name)
print("학번:", Number)
print("학과:", Major)
print("학교:", Grade)